### ISSUE TITLE
Documentation: Perhaps more values when inserting Granting access to Mic for Espanso

### ISSUE THREAD

**Issue by victorcstn** [rohitna/chatgpt-script#4]
First of all, THANK you for the tool. Great concept. 

I found an error when inserting the original insert on the docs. Or at least in my system is missing 4 values as the table seems to have 17 columns. The following worked for me

``
insert into access
   ...> values
   ...> ('kTCCServiceMicrophone','com.federicoterzi.espanso', 0, 2, 2, 1, null, null, null, 'UNUSED', null, 0, 1671466672, null, null, 'UNUSED', 0);
``

**Comment by rohitna** [comment]
Thank you so much! I have updated the documentation.
